FROM node:16.15-alpine

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

# set yarn log level to verbose
ENV YARN_LOG_LEVEL=verbose

CMD ["yarn", "start"]
