# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    image : odekakekun-backend
    container_name: odekakekun-backend_container
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project/backend:/usr/src/
    ports:
      - 8004:8000