# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    image : backend_image
    container_name: backend_container
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/develop
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project/backend:/usr/src/
    ports:
      - 8004:8000
    depends_on:
      - db

  db:
    build:
      context: ./project/backend/db
      dockerfile: Dockerfile
    image : db_image
    container_name: db_container
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres