# docker-composeで分けて記載をしておく
version: "3.8"

services:
  frontend:
    build:
      context: ./project/frontend
      dockerfile: Dockerfile
    image: odekakekun-frontend
    container_name: odekakekun-frontend-container
    networks:
      - odekakekun-net
    volumes:
      - ./project/frontend/:/app/
    ports:
      - 3000:80
    env_file:
      - ./project/frontend/frontend.env
    # command: /bin/sh -c "while :; do sleep 10; done"

  backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    image: odekakekun-backend
    container_name: odekakekun-backend-container
    networks:
      - odekakekun-net
    volumes:
      - ./project/backend:/usr/src/
    ports:
      - 8080:80
    env_file:
      - ./project/backend/backend.env
    # command: /bin/sh -c "while :; do sleep 10; done"

networks:
  odekakekun-net:
