# docker-compose.yml
version: "3.8"

services:
  frontend:
    build:
      context: ./project/frontend
      dockerfile: Dockerfile
    image: odekakekun-frontend
    container_name: odekakekun-frontend-container
    networks:
      - odekakekun-net
    volumes:
      - ./project/frontend/:/app/
    ports:
      - 80:3000
    # command: /bin/sh -c "while :; do sleep 10; done"

  backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    image: odekakekun-backend
    container_name: odekakekun-backend-container
    networks:
      - odekakekun-net
    volumes:
      - ./project/backend:/usr/src/
    ports:
      - 8000:80
    # command: /bin/sh -c "while :; do sleep 10; done"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload

networks:
  odekakekun-net:
