# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./project/frontend
      dockerfile: Dockerfile
    image : odekakekun-frontend
    container_name: odekakekun-frontend-container
    networks:
      - odekakekun-net
    volumes:
      - ./project/frontend:/usr/src/
    ports:
      - 80:3000
    # command: /bin/sh -c "while :; do sleep 10; done"

  backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    image : odekakekun-backend
    container_name: odekakekun-backend-container
    networks:
      - odekakekun-net
    volumes:
      - ./project/backend:/usr/src/
    ports:
      - 8000:80

networks:
  odekakekun-net: