# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    image : odekakekun-backend
    container_name: odekakekun-backend_container
    volumes:
      - ./project/backend:/usr/src/
    ports:
      - 8000:80