# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./project/frontend
      dockerfile: Dockerfile
    image : odekakekun-frontend
    container_name: odekakekun-frontend_container
    networks:
      odekakekun-net
    volumes:
      - ./project/frontend:/usr/src/
    ports:
      - 80:3000

  backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    image : odekakekun-backend
    container_name: odekakekun-backend_container
    networks:
      odekakekun-net
    volumes:
      - ./project/backend:/usr/src/
    ports:
      - 8000:80

networks:
  default:
    external:
      name: odekakekun-net