AWSTemplateFormatVersion: "2010-09-09"
Description: LoadBalancer

Parameters:
  VpcId: # 受け取る値を定義する
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>
    Default: /odekakekun-values/VPCId

  PublicSubnetAId: # 受け取る値を定義する
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /odekakekun-values/PublicSubnetAId

  PublicSubnetCId: # 受け取る値を定義する
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /odekakekun-values/PublicSubnetCId

Resources:
  ########################################################
  ###  Internet ALB
  ########################################################
  InternetAlb:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: "internet-alb"
      Scheme: "internet-facing"
      Tags:
        - Key: Name
          Value: "internet-alb"
        - Key: "access_logs.s3.bucket"
          Value: "-s3b-alb-logs"
      SecurityGroups:
        - !Ref ELBSecurityGroup
      Subnets:
        - !Ref PublicSubnetAId
        - !Ref PublicSubnetCId

  AlbListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref InternetAlb
      # ここをHTTPSでアクセス出来るようにしたい
      Port: 80
      Protocol: HTTP

  ########################################################
  ###  Target Group
  ########################################################
  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      VpcId: !Ref VpcId
      Name: "target-group"
      Protocol: HTTP
      Port: 80
      TargetType: ip

  ########################################################
  ### Security Group for ELB!Ref
  ########################################################
  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELB Security Group
      VpcId: !Ref VpcId
      GroupName: elb-security-group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  ########################################################
  ### SSM Parameter
  ########################################################
  SSMPublicSubnetCId: 
    Type: AWS::SSM::Parameter
    Properties:
      Name: /odekakekun-values/TargetGroup
      Type: String
      Value: !Ref 'TargetGroup'

Outputs:
  TargetGroup:
    Value: !Ref TargetGroup
    Export:
      Name: TargetGroup

  AlbListener:
    Value: !Ref AlbListener
    Export:
      Name: AlbListener