AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECS Task Test

Resources:
  ########################################################
  ### ECS Cluster
  ########################################################
  TestEcsCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: "odekakekun-cluster"

  ########################################################
  ###  ECS LogGroup
  ########################################################
  TestEcsLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/ecs/logs/ecs-group"


Outputs:
  TestEcsCluster:
    Value: !Ref TestEcsCluster
    Export:
      Name: TestEcsCluster

  TestEcsLogGroup:
    Value: !Ref TestEcsLogGroup
    Export:
      Name: TestEcsLogGroup

