AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECS FrontEnd Task & Service

Parameters:
  ECSFrontEndServiceName:
    Type: String
    Default: "odekakekun-frontend-service"

  ECSFrontEndTaskName:
    Type: String
    Default: "odekakekun-frontend-task"

  ECSFrontEndContainerName:
    Type: String
    Default: "odekakekun-frontend-container"

  ECSFrontEndImageName:
    Type: String
    Default: "xxxxxxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/odekakekun-frontend"

  # SSMから取得
  PrivateSubnetAId:
    # SSMで受け取る側はAWSのデータ型に合わせる
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /odekakekun-values/PrivateSubnetAId

  PrivateSubnetCId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /odekakekun-values/PrivateSubnetCId

  ECSCluster:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /odekakekun-values/ECSCluster

  ECSLogGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /odekakekun-values/ECSLogGroup

  TargetGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /odekakekun-values/TargetGroup

  ECSTaskExecutionRole:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /odekakekun-values/ECSTaskExecutionRole

  ECSSecurityGroupId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>
    Default: /odekakekun-values/ECSSecurityGroupId

Resources:
  ########################################################
  ###  ECS FrontEnd TaskDefinition
  ########################################################
  ECSFrontEndTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Cpu: 512
      # コンテナで利用するrole
      TaskRoleArn: !Ref ECSTaskExecutionRole
      # ecs-agent用のrole
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      Family: !Ref ECSFrontEndTaskName
      # Memory足りない時はコンソール側からも確認出来る
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Ref ECSFrontEndContainerName
          Image: !Ref ECSFrontEndImageName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              # !RefはAWSの既に定義されてる変数を参照可能
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: odekakekun
          MemoryReservation: 128
          PortMappings:
            - HostPort: 80
              Protocol: tcp
              ContainerPort: 80

  ########################################################
  ###  ECS FrontEnd ServieDefinition
  ########################################################
  ECSFrontEndService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      PlatformVersion: "1.4.0"
      EnableExecuteCommand: true
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerPort: 80
          ContainerName: !Ref ECSFrontEndContainerName
      NetworkConfiguration:
        AwsvpcConfiguration:
          # もしIG/NAtがないsubnetでここをDISABLEDにするとECRに接続できなくなってImagePull失敗する
          AssignPublicIp: DISABLED
          # vpc_cheap_versionの時はPublicSubnetに置くことになるのでENABLEにしておく
          # AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ECSSecurityGroupId
          Subnets:
            - !Ref PrivateSubnetAId
            - !Ref PrivateSubnetCId
      ServiceName: !Ref ECSFrontEndServiceName
      TaskDefinition: !Ref ECSFrontEndTaskDefinition
