AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECS FrontEnd Task & Service

Parameters:
  # 値をコンソールから受付け
  ECSFrontEndServiceName:
    Type: String
    Default: "odekakekun-frontend-service"

  ECSFrontEndTaskName:
    Type: String
    Default: "odekakekun-frontend-task"

  ECSFrontEndContainerName:
    Type: String
    Default: "odekakekun-frontend-container"

  ECSFrontEndImageName:
    Type: String
    Default: "xxxxxxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/odekakekun-frontend"

  # SSMから取得
  PublicSubnetAId: # 受け取る値を定義する
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /odekakekun-values/PublicSubnetAId

  PublicSubnetCId: # 受け取る値を定義する
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /odekakekun-values/PublicSubnetCId

  ECSCluster:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /odekakekun-values/ECSCluster

  ECSLogGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /odekakekun-values/ECSLogGroup

  TargetGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /odekakekun-values/TargetGroup

  ECSTaskExecutionRole: # 受け取る値を定義する
    Type: AWS::SSM::Parameter::Value<String>
    Default: /odekakekun-values/ECSTaskExecutionRole

  ECSSecurityGroupId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>
    Default: /odekakekun-values/ECSSecurityGroupId

Resources:
  # FrontEnd
  ########################################################
  ###  ECS FrontEnd TaskDefinition
  ########################################################
  ECSFrontEndTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Cpu: 512
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      Family: !Ref ECSFrontEndTaskName
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE

      #ContainerDefinitions
      ContainerDefinitions:
        - Name: !Ref ECSFrontEndContainerName
          Image: !Ref ECSFrontEndImageName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              # AWSの既に定義されてる環境変数のようなものを引っ張ってこれる
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: odekakekun
          MemoryReservation: 128
          PortMappings:
            - HostPort: 80
              Protocol: tcp
              ContainerPort: 80

  ########################################################
  ###  ECS FrontEnd ServieDefinition
  ########################################################
  ECSFrontEndService:
    Type: AWS::ECS::Service
    # ALBは別に切り出したので先にALBを起動させるようにStack間で依存関係をもたせたい
    # DependsOn: ALBListener
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      PlatformVersion: "1.4.0"
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerPort: 80
          ContainerName: !Ref ECSFrontEndContainerName
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ECSSecurityGroupId
          Subnets:
            - !Ref PublicSubnetAId
            - !Ref PublicSubnetCId
      ServiceName: !Ref ECSFrontEndServiceName
      TaskDefinition: !Ref ECSFrontEndTaskDefinition
