name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # /home/runner/work/odekakekun/odekakekun
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run : |
            ls
            
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ../../project/backend/Dockerfile --tag my-image-name:$(date +%s)
